### ISSUE TITLE
Roles in team

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#27]
Rights management in team. There are two roles in team: team owner and team member. 

Acceptance criteria:

- [x] Person who created the team gets a team ownership automatically

**Comment by lheilmann** [comment]
@svitlanakalancha In contrast to our discussion in the last meeting, I decided to implement multiple m:n-Relations between User and Team for both roles 'TeamMember' **and** 'TeamOwner', because a team should be able to have multiple team members and multiple team owners, as well. So a team ownership is not stored in the team, it is stored in a separate join table. Same for a team membership.

**Comment by lheilmann** [comment]
@svitlanakalancha At the moment the user creating the team gets a team ownership automatically (Criteria 2), only if the user is signed in. If not, no team ownership is created. Furthermore the team validation will fail, because a team must have minimum one owner (Criteria 1).

**Comment by lheilmann** [comment]
@svitlanakalancha I assume, a team owner is also a team member. So while creating a new team, the current signed in user gets a team ownership **and** a team membership.

**Comment by svitlanakalancha** [comment]
@lheilmann Regarding criteria 2, if the user isn't signed in, he can't add team at all. Can we implement such behavior?
The second assumption is correct :)

**Comment by lheilmann** [comment]
@svitlanakalancha Yes, we can! That's why I have to talk to other teams, to clarify how route/controller method authorization should be implemented in general. It is definitely possible two restrict the user to create/update/destroy a team. Implementing this behaviour right now will cause many tests that were shipped with the application frame to fail. I will talk to the scrum masters to find a quick solution for that.

**Comment by lheilmann** [comment]
@svitlanakalancha Criteria 3 collides technically with #25. I started to implement a first approach. But I will talk to assignees of #25 to determine intersection of the two issues.

**Comment by bakoe** [comment]
@lheilmann Regarding the validations of `assign_membership_to` and `assign_ownership_to`: I think the methods provided by the already included [cancancan](https://github.com/CanCanCommunity/cancancan) gem could replace the quite “manual” checks introduced in 0c4face. 

Using cancancan, we could use something like:

```ruby
class Ability
  include CanCan::Ability

  def initialize(user)
    …
    if user.present?  # additional permissions for logged in users
      …
      can :assign_membership, Team, team_members: { member: { :id => user.id } }
      can :assign_ownership, Team, team_owners: { owner: { :id => user.id } }
      …
    end
  end
end
```

The advantage of using cancancan is that we could re-use the validations in

- **controllers** (e. g. via `authorize! :assign_membership, @team`) as well as
- **views** (`<% if can? :assign_membership, @team %>`), 

following the DRY principle.

**Comment by lheilmann** [comment]
@bakoe Thanks for the hint! Seems to be **the** way to implement authorization issues in rails. :-) We should focus on that. :+1:

**Comment by lheilmann** [comment]
@svitlanakalancha Please delete criteria 3, because it collides with criterias from #25. The criteria is included and done by @jonasnoki and @tomkellog in the referenced issue.

**Comment by lheilmann** [comment]
_Estimated_ time: 5h
_Actual_ time: 10h
