### ISSUE TITLE
Spike: send emails

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#305]
The system should inform a user about news or events happened on the platform. Notification to user should be send in form of email. 

The goal of the spike is to research a possibility to generate automated emails on the platform and send them to a user.

See #301, #307, #308 

**Important**
Check issues #57 and #149 and communicate with other dev teams

**Comment by jonasnoki** [comment]
## Learnings
### Sending E-Mails 
[MailerBasics](http://guides.rubyonrails.org/action_mailer_basics.html) 
to send e-Mails you need a class that inherits from ActionMailer::Base. Within that class you can define defaults for sending e-mails. If you want you can simply use the rails generator function like this:  
``` 
$ bundle exec rails g mailer test_mailer team_created
      create  app/mailers/test_mailer.rb
      invoke  erb
      create    app/views/test_mailer
      create    app/views/test_mailer/team_created.text.erb
      create    app/views/test_mailer/team_created.html.erb
      invoke  rspec
      create    spec/mailers/test_mailer_spec.rb
      create    spec/fixtures/test_mailer/team_created
      create    spec/mailers/previews/test_mailer_preview.rb
```
This creates most files you need.:
* the general ApplicationMailer which is for defaults, 
* the specific user_mailer as defined in the call, 
* a view directory where you can find 
  * the text and 
  * html templates used when sending the mail and 
* the spec where you test your mailers and 
* the preview class to preview the mail

The Mailer could look like this: 
```
class MatchMailer < ApplicationMailer
  # Notifies a user about an upcoming match
  def match_notification(user, match)
    @user = user
    @match = match
    I18n.with_locale(I18n.default_locale) do
      mail(to: @user.email,
           subject: I18n.t('match_mailer.match_notification.subject', start_time: I18n.localize(@match.start_time))
      )
    end
  end
end 
```
The corresponding view should look like this: 
```
!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
<h1><%= t('.hello', firstname: @user.first_name) %></h1>
<p><%= t('.next_game_info', name: @match.event.name, start_time: I18n.localize(@match.start_time), team_home: @match.team_home.name, team_away: @match.team_away.name, place: @match.place) %></p>
<p><%= t('.have_fun') %></p>
</body>
</html>
```

More settings can be done under ``` config/environments/development.rb ```
There you can set the server settings and other things for the environment (e.g. development, production and test.)

The server settings for production are already done on the dev under 

### Testing E-mails
[Testing Mailers](http://guides.rubyonrails.org/testing.html#testing-your-mailers) 
(link may not be very relevant since they are not using rspec.)

**Comment by lheilmann** [comment]
@jonasnoki Did you test a TestMailer? I wonder if we need to configure a mail server or if it included in the rails environment?
