### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#363]
AS a user
I WANT to see a favicon on website
IN ORDER to simpler find this in all my opened tabs

![Screen Shot 2018-01-16 at 19.01.54.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455f56b7191a379e60c2b50415a4abe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95ef749e44550a6103062f43b.png)

Favicon should be attached to every page.

[favicon.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46ee958c2a818ca7cda5fd53b652fa912a5265296b51a27b23d6e12cbd472c035a5f48ac415b5641a8a88b7aa0a42062c80d55b98e30063e937f03a6aa8317b500bf218d4e87b3ba824cc4e13d37aa.zip)

**Comment by zhamanakov** [comment]
AS a user
I WANT to see a favicon on website
IN ORDER to simpler find this in all my opened tabs

[favicon.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46ee958c2a818ca7cda5fd53b652fa912a5265296b51a27b23d6e12cbd472c035a5f48ac415b5641a8a88b7aa0a42062c80d55b98e30063e937f03a6aa8317b500bf218d4e87b3ba824cc4e13d37aa.zip)

**Comment by jkbe** [comment]
**Estimation: XS (Actual: XS)**
