### ISSUE TITLE
ApplicationMailer is not able to send e-mails via the GMX account provided

### ISSUE THREAD

**Issue by niconomaa** [hpi-swt2/sport-portal#462]
Currently, the error `550-Requested action not taken -- mailbox unavailable` is thrown when automated email notifications are sent. 
Further configuration is needed to be able send mails.

**Comment by bakoe** [comment]
It turned out that `ApplicationMailer`'s `default from: 'from@example.com'` had overwritten the ENV variable `SENDER_EMAIL` (sport.portal@gmx.de) which made GMX return a 550 error. Furthermore, the error was logged in Rails only with the quite unspecific “mailbox unavailable” message; when I tried to send an email via SMTP manually in a SMTP client CLI, I also got a much more specific “Sender address is not allowed” message which pointed into the right direction to fix the bug.

**Comment by bakoe** [comment]
Sadly, the mails do again not work at the moment (Jan 30th 3 p.m.) This may need some more work …

**Comment by bakoe** [comment]
… aaaaand it works again. GMX seems to have had some problems.

**Comment by bakoe** [comment]
Actual time I invested in this issue: 1 h
